//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.269
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CubePower.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CubePower.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon tasktray {
            get {
                object obj = ResourceManager.GetObject("tasktray", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_10 {
            get {
                object obj = ResourceManager.GetObject("tasktray_10", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_100 {
            get {
                object obj = ResourceManager.GetObject("tasktray_100", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_20 {
            get {
                object obj = ResourceManager.GetObject("tasktray_20", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_30 {
            get {
                object obj = ResourceManager.GetObject("tasktray_30", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_40 {
            get {
                object obj = ResourceManager.GetObject("tasktray_40", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_50 {
            get {
                object obj = ResourceManager.GetObject("tasktray_50", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_51 {
            get {
                object obj = ResourceManager.GetObject("tasktray_51", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_52 {
            get {
                object obj = ResourceManager.GetObject("tasktray_52", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_53 {
            get {
                object obj = ResourceManager.GetObject("tasktray_53", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_54 {
            get {
                object obj = ResourceManager.GetObject("tasktray_54", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_55 {
            get {
                object obj = ResourceManager.GetObject("tasktray_55", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_56 {
            get {
                object obj = ResourceManager.GetObject("tasktray_56", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_57 {
            get {
                object obj = ResourceManager.GetObject("tasktray_57", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_58 {
            get {
                object obj = ResourceManager.GetObject("tasktray_58", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_59 {
            get {
                object obj = ResourceManager.GetObject("tasktray_59", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_60 {
            get {
                object obj = ResourceManager.GetObject("tasktray_60", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_61 {
            get {
                object obj = ResourceManager.GetObject("tasktray_61", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_62 {
            get {
                object obj = ResourceManager.GetObject("tasktray_62", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_63 {
            get {
                object obj = ResourceManager.GetObject("tasktray_63", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_64 {
            get {
                object obj = ResourceManager.GetObject("tasktray_64", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_65 {
            get {
                object obj = ResourceManager.GetObject("tasktray_65", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_66 {
            get {
                object obj = ResourceManager.GetObject("tasktray_66", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_67 {
            get {
                object obj = ResourceManager.GetObject("tasktray_67", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_68 {
            get {
                object obj = ResourceManager.GetObject("tasktray_68", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_69 {
            get {
                object obj = ResourceManager.GetObject("tasktray_69", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_70 {
            get {
                object obj = ResourceManager.GetObject("tasktray_70", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_71 {
            get {
                object obj = ResourceManager.GetObject("tasktray_71", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_72 {
            get {
                object obj = ResourceManager.GetObject("tasktray_72", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_73 {
            get {
                object obj = ResourceManager.GetObject("tasktray_73", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_74 {
            get {
                object obj = ResourceManager.GetObject("tasktray_74", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_75 {
            get {
                object obj = ResourceManager.GetObject("tasktray_75", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_76 {
            get {
                object obj = ResourceManager.GetObject("tasktray_76", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_77 {
            get {
                object obj = ResourceManager.GetObject("tasktray_77", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_78 {
            get {
                object obj = ResourceManager.GetObject("tasktray_78", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_79 {
            get {
                object obj = ResourceManager.GetObject("tasktray_79", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_80 {
            get {
                object obj = ResourceManager.GetObject("tasktray_80", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_81 {
            get {
                object obj = ResourceManager.GetObject("tasktray_81", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_82 {
            get {
                object obj = ResourceManager.GetObject("tasktray_82", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_83 {
            get {
                object obj = ResourceManager.GetObject("tasktray_83", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_84 {
            get {
                object obj = ResourceManager.GetObject("tasktray_84", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_85 {
            get {
                object obj = ResourceManager.GetObject("tasktray_85", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_86 {
            get {
                object obj = ResourceManager.GetObject("tasktray_86", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_87 {
            get {
                object obj = ResourceManager.GetObject("tasktray_87", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_88 {
            get {
                object obj = ResourceManager.GetObject("tasktray_88", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_89 {
            get {
                object obj = ResourceManager.GetObject("tasktray_89", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_90 {
            get {
                object obj = ResourceManager.GetObject("tasktray_90", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_91 {
            get {
                object obj = ResourceManager.GetObject("tasktray_91", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_92 {
            get {
                object obj = ResourceManager.GetObject("tasktray_92", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_93 {
            get {
                object obj = ResourceManager.GetObject("tasktray_93", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_94 {
            get {
                object obj = ResourceManager.GetObject("tasktray_94", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_95 {
            get {
                object obj = ResourceManager.GetObject("tasktray_95", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_96 {
            get {
                object obj = ResourceManager.GetObject("tasktray_96", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_97 {
            get {
                object obj = ResourceManager.GetObject("tasktray_97", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_98 {
            get {
                object obj = ResourceManager.GetObject("tasktray_98", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tasktray_99 {
            get {
                object obj = ResourceManager.GetObject("tasktray_99", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
